---

- name: restart samba
  shell: restart smbd
  sudo: yes
  when: ansible_distribution == 'Ubuntu'

- name: restart winbind
  shell: restart winbind
  sudo: yes
  when: ansible_distribution == 'Ubuntu'

- name: restart lightdm
  service: name=lightdm state=restarted
  sudo: yes

- name: restart networking
  service: name=networking state=restarted
  sudo: yes
