---

- name: Cambio configurazione lightdm
  lineinfile: dest=/etc/lightdm/lightdm.conf.d/90-edubuntu.conf line={{ item }} state=present
  with_items:
    - "allow-guest=false"
    - "greeter-hide-users=true"
    - "greeter-show-manual-login=true"
  when: ansible_distribution == "Ubuntu"
  sudo: yes
  notify: restart lightdm
