---

- name: Backup nsswitch.conf originale
  shell: test -f /etc/nsswitch.conf.orig || cp /etc/nsswitch.conf /etc/nsswitch.conf.orig
  sudo: yes

- name: Configurazione nsswitch.conf 
  copy: src=nsswitch.conf dest=/etc/nsswitch.conf
  sudo: yes
