---

- name: Backup smb.conf originale
  shell: cp /etc/samba/smb.conf /etc/samba/smb.conf.orig
  sudo: yes

- name: Configurazione smb.conf
  template: src=smb.conf dest=/etc/samba/smb.conf validate='testparm -s %s'
  sudo: yes

- name: Creazione home base
  shell: mkdir -p /home/{{ domainshort }}
  sudo: yes
